title:        Maurizio Attanasi
email:        maurizio.attanasi@gmail.com
description:  The difficult done immediately, the impossible by appointment only
author:       Maurizio Attanasi
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://maurizioattanasi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Social Profiles
github_username:        maurizioattanasi
linkedin_username:      maurizioattanasi
stackoverflow_username: 6952943/maurizio-attanasi
twitter_username:       mau970

google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
# theme: jekyll-theme-clean-blog
remote_theme: jekyll-theme-clean-blog
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
sass:
  sass_dir: _sass
  # style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
